spring.application.name=reviews
server.port=8084

# PostgreSQL DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/db_reviews
spring.datasource.username=ecommers
spring.datasource.password=ecommers_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Feign clients
feign.client.product-url=http://localhost:8081
feign.client.user-url=http://localhost:8082
