server.port=8084
spring.application.name=reviews

# Feign clients
feign.client.product-url=http://localhost:8081
feign.client.user-url=http://localhost:8082

# DataSource Oracle
spring.datasource.url=jdbc:oracle:thin:@localhost:1523/FREEPDB1
spring.datasource.username=reviews_user
spring.datasource.password=reviews_pass
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# Flyway
spring.flyway.enabled=false