CREATE TABLE reviews (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id     NUMBER(19)    NOT NULL,
    user_id        NUMBER(19)    NOT NULL,
    rating         NUMBER(1)     NOT NULL CHECK (rating BETWEEN 1 AND 5),
    review_comment VARCHAR2(1000)
);
